import type { EconomicIndicator, MacroComment, ResearchReport, DataPoint, EconomicEvent } from "./types";

// ────────────────────────────────────────────
// 시계열 더미 데이터 생성 헬퍼
// ────────────────────────────────────────────
// ── 오늘 날짜 (동적 — 새로고침마다 갱신) ────────
const _TODAY = new Date().toISOString().slice(0, 10);

// 마지막 영업일(주말이면 금요일)
function lastBusinessDay(): string {
  const d = new Date();
  const day = d.getDay();
  if (day === 0) d.setDate(d.getDate() - 2); // 일 → 금
  if (day === 6) d.setDate(d.getDate() - 1); // 토 → 금
  return d.toISOString().slice(0, 10);
}
const _LAST_BD = lastBusinessDay();

// 이번 달 1일
const _THIS_MONTH = new Date(new Date().getFullYear(), new Date().getMonth(), 1)
  .toISOString().slice(0, 10);

function generateMonthly(
  baseValue: number,
  _months: number,   // 무시 — 오늘 기준 동적 생성
  volatility: number,
  trend: number = 0
): DataPoint[] {
  const points: DataPoint[] = [];
  let value = baseValue;
  const start = new Date("2023-01-01");
  const today = new Date();
  const d = new Date(start);
  while (d <= today) {
    const dateStr = d.toISOString().slice(0, 10);
    const change = (Math.random() - 0.48) * volatility + trend;
    value = Math.max(0, value + change);
    points.push({ date: dateStr, value: parseFloat(value.toFixed(2)) });
    d.setMonth(d.getMonth() + 1);
  }
  return points;
}

function generateDaily(
  baseValue: number,
  _days: number,     // 무시 — 오늘 기준 동적 생성
  volatility: number,
  trend: number = 0
): DataPoint[] {
  const points: DataPoint[] = [];
  let value = baseValue;
  const start = new Date("2023-01-02");
  const today = new Date();
  today.setHours(23, 59, 59, 0);
  const d = new Date(start);
  while (d <= today) {
    // 주말 제외
    if (d.getDay() !== 0 && d.getDay() !== 6) {
      const dateStr = d.toISOString().slice(0, 10);
      const change = (Math.random() - 0.48) * volatility + trend;
      value = Math.max(0, value + change);
      points.push({ date: dateStr, value: parseFloat(value.toFixed(2)) });
    }
    d.setDate(d.getDate() + 1);
  }
  return points;
}

// ────────────────────────────────────────────
// 국내 경제 지표
// ────────────────────────────────────────────
export const domesticIndicators: EconomicIndicator[] = [
  {
    id: "kospi",
    name: "KOSPI",
    nameKo: "코스피",
    category: "주가",
    currentValue: 2601.36,
    previousValue: 2548.20,
    unit: "pt",
    source: "KRX",
    sourceUrl: "https://www.krx.co.kr",
    region: "domestic",
    trend: "up",
    changeAbs: 53.16,
    changePct: 2.09,
    timeSeries: generateDaily(2500, 780, 30, 0.1),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "kosdaq",
    name: "KOSDAQ",
    nameKo: "코스닥",
    category: "주가",
    currentValue: 737.82,
    previousValue: 726.94,
    unit: "pt",
    source: "KRX",
    sourceUrl: "https://www.krx.co.kr",
    region: "domestic",
    trend: "up",
    changeAbs: 10.88,
    changePct: 1.50,
    timeSeries: generateDaily(760, 780, 12, -0.02),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "krw-usd",
    name: "KRW/USD",
    nameKo: "원/달러 환율",
    category: "환율",
    currentValue: 1382.50,
    previousValue: 1395.00,
    unit: "원",
    source: "한국은행",
    sourceUrl: "https://www.bok.or.kr",
    region: "domestic",
    trend: "down",
    changeAbs: -12.50,
    changePct: -0.90,
    timeSeries: generateDaily(1290, 780, 8, 0.08),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "krw-jpy",
    name: "KRW/JPY",
    nameKo: "원/엔 환율",
    category: "환율",
    currentValue: 9.48,
    previousValue: 9.55,
    unit: "원",
    source: "한국은행",
    sourceUrl: "https://www.bok.or.kr",
    region: "domestic",
    trend: "down",
    changeAbs: -0.07,
    changePct: -0.73,
    timeSeries: generateDaily(9.20, 780, 0.1, 0.003),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "kor-3y-bond",
    name: "KTB 3Y",
    nameKo: "국고채 3년",
    category: "금리",
    currentValue: 2.68,
    previousValue: 2.74,
    unit: "%",
    source: "한국은행",
    sourceUrl: "https://www.bok.or.kr",
    region: "domestic",
    trend: "down",
    changeAbs: -0.06,
    changePct: -2.19,
    timeSeries: generateMonthly(3.80, 36, 0.12, -0.03),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "kor-10y-bond",
    name: "KTB 10Y",
    nameKo: "국고채 10년",
    category: "금리",
    currentValue: 2.92,
    previousValue: 2.99,
    unit: "%",
    source: "한국은행",
    sourceUrl: "https://www.bok.or.kr",
    region: "domestic",
    trend: "down",
    changeAbs: -0.07,
    changePct: -2.34,
    timeSeries: generateMonthly(4.10, 36, 0.15, -0.04),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "kor-base-rate",
    name: "Base Rate",
    nameKo: "기준금리",
    category: "금리",
    currentValue: 2.75,
    previousValue: 3.00,
    unit: "%",
    source: "한국은행",
    sourceUrl: "https://www.bok.or.kr",
    region: "domestic",
    trend: "down",
    changeAbs: -0.25,
    changePct: -8.33,
    timeSeries: generateMonthly(3.50, 36, 0.05, -0.025),
    updatedAt: "2026-02-27",
    frequency: "monthly",
  },
  {
    id: "kor-cpi",
    name: "CPI (YoY)",
    nameKo: "소비자물가(전년비)",
    category: "물가",
    currentValue: 1.9,
    previousValue: 2.1,
    unit: "%",
    source: "통계청",
    sourceUrl: "https://kostat.go.kr",
    region: "domestic",
    trend: "down",
    changeAbs: -0.2,
    changePct: -9.52,
    timeSeries: generateMonthly(5.1, 36, 0.2, -0.09),
    updatedAt: "2026-05-02",
    frequency: "monthly",
  },
  {
    id: "kor-ppi",
    name: "PPI (YoY)",
    nameKo: "생산자물가(전년비)",
    category: "물가",
    currentValue: 1.4,
    previousValue: 1.7,
    unit: "%",
    source: "한국은행",
    sourceUrl: "https://www.bok.or.kr",
    region: "domestic",
    trend: "down",
    changeAbs: -0.3,
    changePct: -17.65,
    timeSeries: generateMonthly(6.2, 36, 0.3, -0.14),
    updatedAt: "2026-04-25",
    frequency: "monthly",
  },
  {
    id: "kor-gdp",
    name: "GDP Growth",
    nameKo: "GDP 성장률(전년비)",
    category: "성장",
    currentValue: 1.2,
    previousValue: 1.4,
    unit: "%",
    source: "한국은행",
    sourceUrl: "https://www.bok.or.kr",
    region: "domestic",
    trend: "down",
    changeAbs: -0.2,
    changePct: -14.29,
    timeSeries: generateMonthly(2.5, 12, 0.3, -0.1).concat(
      generateMonthly(1.8, 24, 0.2, -0.025)
    ),
    updatedAt: "2026-04-24",
    frequency: "quarterly",
  },
  {
    id: "kor-unemployment",
    name: "Unemployment",
    nameKo: "실업률",
    category: "고용",
    currentValue: 3.1,
    previousValue: 2.9,
    unit: "%",
    source: "통계청",
    sourceUrl: "https://kostat.go.kr",
    region: "domestic",
    trend: "up",
    changeAbs: 0.2,
    changePct: 6.90,
    timeSeries: generateMonthly(2.9, 36, 0.1, 0.006),
    updatedAt: "2026-05-14",
    frequency: "monthly",
  },
  {
    id: "kor-m2",
    name: "M2",
    nameKo: "광의통화(M2)",
    category: "기타",
    currentValue: 3987.4,
    previousValue: 3941.2,
    unit: "조원",
    source: "한국은행",
    sourceUrl: "https://www.bok.or.kr",
    region: "domestic",
    trend: "up",
    changeAbs: 46.2,
    changePct: 1.17,
    timeSeries: generateMonthly(3600, 36, 20, 10.8),
    updatedAt: "2026-04-30",
    frequency: "monthly",
  },
  {
    id: "kor-household-debt",
    name: "Household Debt",
    nameKo: "가계부채",
    category: "기타",
    currentValue: 1896.2,
    previousValue: 1887.5,
    unit: "조원",
    source: "한국은행",
    sourceUrl: "https://www.bok.or.kr",
    region: "domestic",
    trend: "up",
    changeAbs: 8.7,
    changePct: 0.46,
    timeSeries: generateMonthly(1750, 36, 10, 4.1),
    updatedAt: "2026-03-31",
    frequency: "quarterly",
  },
  {
    id: "kor-current-account",
    name: "Current Account",
    nameKo: "경상수지",
    category: "기타",
    currentValue: 68.4,
    previousValue: 62.1,
    unit: "억달러",
    source: "한국은행",
    sourceUrl: "https://www.bok.or.kr",
    region: "domestic",
    trend: "up",
    changeAbs: 6.3,
    changePct: 10.15,
    timeSeries: generateMonthly(30, 36, 15, 1.1),
    updatedAt: "2026-04-30",
    frequency: "monthly",
  },
  {
    id: "kor-investor-deposit",
    name: "Investor Deposit",
    nameKo: "투자자예탁금",
    category: "기타",
    currentValue: 52.3,
    previousValue: 49.8,
    unit: "조원",
    source: "금융투자협회",
    sourceUrl: "https://www.kofia.or.kr",
    region: "domestic",
    trend: "up",
    changeAbs: 2.5,
    changePct: 5.02,
    timeSeries: generateMonthly(38, 36, 3, 0.4),
    updatedAt: "2026-05-22",
    frequency: "daily",
  },
  {
    id: "cd-91d",
    name: "CD 91D",
    nameKo: "CD금리(91일)",
    category: "금리",
    currentValue: 3.65,
    previousValue: 3.68,
    unit: "%",
    source: "한국은행",
    sourceUrl: "https://www.bok.or.kr",
    region: "domestic",
    trend: "down",
    changeAbs: -0.03,
    changePct: -0.82,
    timeSeries: generateMonthly(4.10, 36, 0.08, -0.013),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "cp-91d",
    name: "CP 91D",
    nameKo: "CP금리(91일)",
    category: "금리",
    currentValue: 3.88,
    previousValue: 3.92,
    unit: "%",
    source: "한국은행",
    sourceUrl: "https://www.bok.or.kr",
    region: "domestic",
    trend: "down",
    changeAbs: -0.04,
    changePct: -1.02,
    timeSeries: generateMonthly(4.35, 36, 0.09, -0.013),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "ktb-30y",
    name: "KTB 30Y",
    nameKo: "국고채 30년",
    category: "금리",
    currentValue: 3.08,
    previousValue: 3.15,
    unit: "%",
    source: "한국은행",
    sourceUrl: "https://www.bok.or.kr",
    region: "domestic",
    trend: "down",
    changeAbs: -0.07,
    changePct: -2.22,
    timeSeries: generateMonthly(4.25, 36, 0.14, -0.033),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "mss-1y",
    name: "MSS 1Y",
    nameKo: "통안채 1년",
    category: "금리",
    currentValue: 2.62,
    previousValue: 2.68,
    unit: "%",
    source: "한국은행",
    sourceUrl: "https://www.bok.or.kr",
    region: "domestic",
    trend: "down",
    changeAbs: -0.06,
    changePct: -2.24,
    timeSeries: generateMonthly(3.70, 36, 0.10, -0.030),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "krw-eur",
    name: "KRW/EUR",
    nameKo: "원/유로 환율",
    category: "환율",
    currentValue: 1559.4,
    previousValue: 1567.1,
    unit: "원",
    source: "한국은행",
    sourceUrl: "https://www.bok.or.kr",
    region: "domestic",
    trend: "down",
    changeAbs: -7.7,
    changePct: -0.49,
    timeSeries: generateDaily(1380, 780, 12, 0.23),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
];

// ────────────────────────────────────────────
// 국외 경제 지표
// ────────────────────────────────────────────
export const foreignIndicators: EconomicIndicator[] = [
  {
    id: "sp500",
    name: "S&P 500",
    nameKo: "S&P 500",
    category: "주가",
    currentValue: 5306.04,
    previousValue: 5244.39,
    unit: "pt",
    source: "Yahoo Finance",
    sourceUrl: "https://finance.yahoo.com/quote/%5EGSPC",
    region: "foreign",
    trend: "up",
    changeAbs: 61.65,
    changePct: 1.18,
    timeSeries: generateDaily(4200, 780, 50, 1.4),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "nasdaq",
    name: "NASDAQ",
    nameKo: "나스닥",
    category: "주가",
    currentValue: 16920.80,
    previousValue: 16742.39,
    unit: "pt",
    source: "Yahoo Finance",
    sourceUrl: "https://finance.yahoo.com/quote/%5EIXIC",
    region: "foreign",
    trend: "up",
    changeAbs: 178.41,
    changePct: 1.07,
    timeSeries: generateDaily(13000, 780, 180, 4.2),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "dxy",
    name: "DXY",
    nameKo: "달러 인덱스",
    category: "환율",
    currentValue: 99.84,
    previousValue: 100.21,
    unit: "pt",
    source: "FRED",
    sourceUrl: "https://fred.stlouisfed.org/series/DTWEXBGS",
    region: "foreign",
    trend: "down",
    changeAbs: -0.37,
    changePct: -0.37,
    timeSeries: generateDaily(103, 780, 0.6, -0.004),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "us-10y",
    name: "US 10Y",
    nameKo: "미국채 10년",
    category: "금리",
    currentValue: 4.51,
    previousValue: 4.59,
    unit: "%",
    source: "FRED",
    sourceUrl: "https://fred.stlouisfed.org/series/DGS10",
    region: "foreign",
    trend: "down",
    changeAbs: -0.08,
    changePct: -1.74,
    timeSeries: generateDaily(3.90, 780, 0.08, 0.001),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "us-2y",
    name: "US 2Y",
    nameKo: "미국채 2년",
    category: "금리",
    currentValue: 4.01,
    previousValue: 4.10,
    unit: "%",
    source: "FRED",
    sourceUrl: "https://fred.stlouisfed.org/series/DGS2",
    region: "foreign",
    trend: "down",
    changeAbs: -0.09,
    changePct: -2.20,
    timeSeries: generateDaily(4.80, 780, 0.07, -0.002),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "fed-rate",
    name: "Fed Funds Rate",
    nameKo: "연방기금금리",
    category: "금리",
    currentValue: 4.25,
    previousValue: 4.50,
    unit: "%",
    source: "FRED",
    sourceUrl: "https://fred.stlouisfed.org/series/FEDFUNDS",
    region: "foreign",
    trend: "down",
    changeAbs: -0.25,
    changePct: -5.56,
    timeSeries: generateMonthly(5.33, 36, 0.05, -0.03),
    updatedAt: "2026-05-01",
    frequency: "monthly",
  },
  {
    id: "us-cpi",
    name: "US CPI (YoY)",
    nameKo: "미국 소비자물가(전년비)",
    category: "물가",
    currentValue: 2.3,
    previousValue: 2.4,
    unit: "%",
    source: "FRED",
    sourceUrl: "https://fred.stlouisfed.org/series/CPIAUCSL",
    region: "foreign",
    trend: "down",
    changeAbs: -0.1,
    changePct: -4.17,
    timeSeries: generateMonthly(6.4, 36, 0.2, -0.12),
    updatedAt: "2026-05-13",
    frequency: "monthly",
  },
  {
    id: "us-pce",
    name: "US Core PCE",
    nameKo: "미국 근원 PCE",
    category: "물가",
    currentValue: 2.6,
    previousValue: 2.7,
    unit: "%",
    source: "FRED",
    sourceUrl: "https://fred.stlouisfed.org/series/PCEPILFE",
    region: "foreign",
    trend: "down",
    changeAbs: -0.1,
    changePct: -3.70,
    timeSeries: generateMonthly(4.7, 36, 0.15, -0.06),
    updatedAt: "2026-04-30",
    frequency: "monthly",
  },
  {
    id: "us-unemployment",
    name: "US Unemployment",
    nameKo: "미국 실업률",
    category: "고용",
    currentValue: 4.2,
    previousValue: 4.1,
    unit: "%",
    source: "FRED",
    sourceUrl: "https://fred.stlouisfed.org/series/UNRATE",
    region: "foreign",
    trend: "up",
    changeAbs: 0.1,
    changePct: 2.44,
    timeSeries: generateMonthly(3.4, 36, 0.1, 0.022),
    updatedAt: "2026-05-02",
    frequency: "monthly",
  },
  {
    id: "us-nonfarm",
    name: "Nonfarm Payrolls",
    nameKo: "비농업 고용",
    category: "고용",
    currentValue: 177,
    previousValue: 228,
    unit: "천명",
    source: "FRED",
    sourceUrl: "https://fred.stlouisfed.org/series/PAYEMS",
    region: "foreign",
    trend: "down",
    changeAbs: -51,
    changePct: -22.37,
    timeSeries: generateMonthly(220, 36, 30, -1.2),
    updatedAt: "2026-05-02",
    frequency: "monthly",
  },
  {
    id: "us-gdp",
    name: "US GDP Growth",
    nameKo: "미국 GDP 성장률",
    category: "성장",
    currentValue: 2.4,
    previousValue: 2.8,
    unit: "%",
    source: "FRED",
    sourceUrl: "https://fred.stlouisfed.org/series/A191RL1Q225SBEA",
    region: "foreign",
    trend: "down",
    changeAbs: -0.4,
    changePct: -14.29,
    timeSeries: generateMonthly(2.9, 12, 0.4, -0.05).concat(
      generateMonthly(2.5, 24, 0.3, -0.03)
    ),
    updatedAt: "2026-04-30",
    frequency: "quarterly",
  },
  {
    id: "wti",
    name: "WTI Crude",
    nameKo: "WTI 유가",
    category: "가격",
    currentValue: 61.53,
    previousValue: 63.85,
    unit: "달러",
    source: "Yahoo Finance",
    sourceUrl: "https://finance.yahoo.com/quote/CL%3DF",
    region: "foreign",
    trend: "down",
    changeAbs: -2.32,
    changePct: -3.63,
    timeSeries: generateDaily(80, 780, 2.5, -0.025),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "gold",
    name: "Gold",
    nameKo: "금 가격",
    category: "가격",
    currentValue: 3306.40,
    previousValue: 3284.10,
    unit: "달러",
    source: "Yahoo Finance",
    sourceUrl: "https://finance.yahoo.com/quote/GC%3DF",
    region: "foreign",
    trend: "up",
    changeAbs: 22.30,
    changePct: 0.68,
    timeSeries: generateDaily(1900, 780, 20, 0.9),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "vix",
    name: "VIX",
    nameKo: "공포지수 (VIX)",
    category: "기타",
    currentValue: 20.14,
    previousValue: 22.38,
    unit: "pt",
    source: "Yahoo Finance",
    sourceUrl: "https://finance.yahoo.com/quote/%5EVIX",
    region: "foreign",
    trend: "down",
    changeAbs: -2.24,
    changePct: -10.01,
    timeSeries: generateDaily(15, 780, 3, 0.007),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "brent",
    name: "Brent Crude",
    nameKo: "브렌트유",
    category: "가격",
    currentValue: 65.28,
    previousValue: 67.40,
    unit: "달러",
    source: "Yahoo Finance",
    sourceUrl: "https://finance.yahoo.com/quote/BZ%3DF",
    region: "foreign",
    trend: "down",
    changeAbs: -2.12,
    changePct: -3.15,
    timeSeries: generateDaily(84, 780, 2.6, -0.027),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "bitcoin",
    name: "Bitcoin",
    nameKo: "비트코인",
    category: "가격",
    currentValue: 107420,
    previousValue: 104850,
    unit: "달러",
    source: "Yahoo Finance",
    sourceUrl: "https://finance.yahoo.com/quote/BTC-USD",
    region: "foreign",
    trend: "up",
    changeAbs: 2570,
    changePct: 2.45,
    timeSeries: generateDaily(30000, 780, 2500, 100),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "lithium-carbonate",
    name: "Lithium Carbonate",
    nameKo: "탄산리튬",
    category: "가격",
    currentValue: 9820,
    previousValue: 10250,
    unit: "달러/톤",
    source: "SMM",
    sourceUrl: "https://www.metal.com",
    region: "foreign",
    trend: "down",
    changeAbs: -430,
    changePct: -4.20,
    timeSeries: generateMonthly(70000, 12, 5000, -3500).concat(
      generateMonthly(20000, 24, 2000, -430)
    ),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "ddr5",
    name: "DDR5 16Gb",
    nameKo: "DDR5 (16Gb)",
    category: "가격",
    currentValue: 1.85,
    previousValue: 1.92,
    unit: "달러/Gb",
    source: "DRAMeXchange",
    sourceUrl: "https://www.dramexchange.com",
    region: "foreign",
    trend: "down",
    changeAbs: -0.07,
    changePct: -3.65,
    timeSeries: generateMonthly(3.20, 36, 0.15, -0.038),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "china-csi300",
    name: "CSI 300",
    nameKo: "중국 CSI 300",
    category: "주가",
    currentValue: 3812.44,
    previousValue: 3789.06,
    unit: "pt",
    source: "Yahoo Finance",
    sourceUrl: "https://finance.yahoo.com/quote/000300.SS",
    region: "foreign",
    trend: "up",
    changeAbs: 23.38,
    changePct: 0.62,
    timeSeries: generateDaily(4200, 780, 40, -0.5),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "us-30y",
    name: "US 30Y",
    nameKo: "미국채 30년",
    category: "금리",
    currentValue: 4.82,
    previousValue: 4.91,
    unit: "%",
    source: "FRED",
    sourceUrl: "https://fred.stlouisfed.org/series/DGS30",
    region: "foreign",
    trend: "down",
    changeAbs: -0.09,
    changePct: -1.83,
    timeSeries: generateDaily(4.20, 780, 0.09, 0.001),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "eur-usd",
    name: "EUR/USD",
    nameKo: "유로/달러",
    category: "환율",
    currentValue: 1.1285,
    previousValue: 1.1224,
    unit: "달러",
    source: "Yahoo Finance",
    sourceUrl: "https://finance.yahoo.com/quote/EURUSD=X",
    region: "foreign",
    trend: "up",
    changeAbs: 0.0061,
    changePct: 0.54,
    timeSeries: generateDaily(1.06, 780, 0.008, 0.00009),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
  {
    id: "usd-jpy",
    name: "USD/JPY",
    nameKo: "달러/엔",
    category: "환율",
    currentValue: 143.52,
    previousValue: 144.82,
    unit: "엔",
    source: "Yahoo Finance",
    sourceUrl: "https://finance.yahoo.com/quote/JPY=X",
    region: "foreign",
    trend: "down",
    changeAbs: -1.30,
    changePct: -0.90,
    timeSeries: generateDaily(130, 780, 1.2, 0.018),
    updatedAt: _LAST_BD,
    frequency: "daily",
  },
];

// ────────────────────────────────────────────
// 핵심 코멘트 더미 데이터
// ────────────────────────────────────────────
export const macroComments: MacroComment[] = [
  // 국내
  {
    id: "dom-comment-1",
    region: "domestic",
    title: "한국은행 금통위: 추가 인하 여지 열어뒀으나 신중한 스탠스 유지",
    body: "한국은행은 5월 금통위에서 기준금리를 2.75%로 동결했다. 물가가 목표수준(2%) 근접했으나, 가계부채 재팽창 우려와 원/달러 환율 변동성을 경계하며 추가 인하 시점을 늦추고 있다. 내수 회복 속도가 예상보다 느린 상황에서 하반기 1회 추가 인하 가능성은 열려 있다.",
    source: "한국은행 금융통화위원회",
    sourceUrl: "https://www.bok.or.kr/portal/main/contents.do?menuNo=200761",
    publishedAt: "2026-05-22",
    tags: ["금리", "한국은행", "통화정책"],
    relatedIndicators: ["kor-base-rate", "kor-cpi", "kor-3y-bond"],
  },
  {
    id: "dom-comment-2",
    region: "domestic",
    title: "수출 회복세 지속, 반도체 중심 IT 업황 개선",
    body: "4월 수출은 전년 동기 대비 +8.3% 증가하며 7개월 연속 플러스 행진을 이어갔다. 반도체(+34.2%)가 전체를 견인했으나, 대중국 수출 비중 축소와 미국發 관세 리스크가 하반기 불확실성 요인으로 남아 있다. 코스피는 반도체·IT 중심 강세로 2,600선 회복을 시도하고 있다.",
    source: "산업통상자원부",
    sourceUrl: "https://www.motie.go.kr",
    publishedAt: "2026-05-01",
    tags: ["수출", "반도체", "무역"],
    relatedIndicators: ["kospi", "kor-current-account"],
  },
  {
    id: "dom-comment-3",
    region: "domestic",
    title: "가계부채 증가 재개, 가계 DSR 3단계 시행 앞두고 막바지 수요 집중",
    body: "2분기 들어 주택담보대출을 중심으로 가계부채가 재차 늘어나고 있다. 6월 DSR 3단계 시행 전 수요가 집중되는 양상이다. 당국은 스트레스 DSR 비율 상향과 비은행권 총량관리를 통해 속도 조절을 시도 중이나, 부동산 시장 반등이 변수다.",
    source: "금융위원회",
    sourceUrl: "https://www.fsc.go.kr",
    publishedAt: "2026-05-15",
    tags: ["가계부채", "DSR", "부동산"],
    relatedIndicators: ["kor-household-debt", "kor-m2"],
  },
  // 국외
  {
    id: "for-comment-1",
    region: "foreign",
    title: "Fed, 하반기 2회 인하 전망 유지…데이터 의존적 스탠스",
    body: "5월 FOMC 의사록에서 연준 위원들은 인플레이션이 2% 목표로 수렴 중이나 속도가 느리다고 평가했다. 노동시장은 견조하지만 냉각 신호가 점진적으로 나타나고 있다. 시장은 9월·12월 각각 25bp 인하를 기본 시나리오로 설정하고 있으며, 관세 리스크가 상방 요인이다.",
    source: "Fed (FOMC Minutes)",
    sourceUrl: "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm",
    publishedAt: "2026-05-21",
    tags: ["Fed", "금리인하", "통화정책"],
    relatedIndicators: ["fed-rate", "us-cpi", "us-10y"],
  },
  {
    id: "for-comment-2",
    region: "foreign",
    title: "미국 4월 CPI 2.3%, 예상치 하회…인플레이션 둔화 확인",
    body: "4월 미국 CPI는 전년 동기 대비 2.3%로 시장 예상(2.4%)을 하회했다. 에너지 가격 하락(-2.1%)과 주거비 상승세 둔화가 주 원인이다. 근원 CPI는 2.8%로 여전히 목표 수준을 상회하나 방향성은 우호적이다. 채권시장은 금리 하락으로 반응했으며, 달러는 약세를 보였다.",
    source: "U.S. Bureau of Labor Statistics",
    sourceUrl: "https://www.bls.gov/cpi",
    publishedAt: "2026-05-13",
    tags: ["CPI", "인플레이션", "미국"],
    relatedIndicators: ["us-cpi", "us-10y", "dxy"],
  },
  {
    id: "for-comment-3",
    region: "foreign",
    title: "미·중 무역 협상 진전, 90일 관세 유예 합의",
    body: "미국과 중국은 제네바 회담에서 상호 관세를 일부 인하하고 90일간 추가 부과를 유예하기로 합의했다. 미국은 중국산 제품에 부과하던 145% 관세를 30%대로 낮추기로 했으며, 중국 역시 미국산 제품에 대한 보복관세를 완화했다. 이번 합의로 글로벌 무역 불확실성이 일부 해소되며 위험자산 선호 심리가 개선됐다.",
    source: "U.S. Trade Representative",
    sourceUrl: "https://ustr.gov",
    publishedAt: "2026-05-12",
    tags: ["무역전쟁", "관세", "미중관계"],
    relatedIndicators: ["sp500", "dxy", "gold", "wti"],
  },
  {
    id: "for-comment-4",
    region: "foreign",
    title: "ECB 6월 추가 인하 신호…유로존 성장 모멘텀 약화",
    body: "ECB 라가르드 총재는 인플레이션이 2% 목표에 근접했다며 6월 25bp 인하를 시사했다. 독일을 중심으로 제조업 경기가 부진한 가운데, 성장 지원을 위한 통화정책 완화 필요성이 커지고 있다. 유로/달러는 1.13대로 상승하며 강세를 나타내고 있다.",
    source: "European Central Bank",
    sourceUrl: "https://www.ecb.europa.eu",
    publishedAt: "2026-05-20",
    tags: ["ECB", "유로존", "금리인하"],
    relatedIndicators: ["dxy", "us-10y"],
  },
];

// ────────────────────────────────────────────
// 리서치 리포트 더미 데이터
// ────────────────────────────────────────────
export const researchReports: ResearchReport[] = [
  {
    id: "rr-001",
    region: "domestic",
    title: "글로벌 매크로 위클리: 관세 불확실성 완화, 위험자산 선호 재개",
    publisher: "삼성증권",
    publishedAt: "2026-05-25",
    url: "https://www.samsungpop.com",
    summary: "미중 관세 유예 합의 이후 글로벌 위험 선호 심리 회복. 한국 수출 수혜 가능성과 환율 안정 전망.",
    tags: ["글로벌매크로", "관세", "환율"],
  },
  {
    id: "rr-002",
    region: "domestic",
    title: "채권 전략: 금통위 동결 이후 단기 금리 방향성",
    publisher: "KB증권",
    publishedAt: "2026-05-25",
    url: "https://www.kbsec.com",
    summary: "금통위 동결 결정 이후 단기 금리는 박스권 예상. 3년물 2.6~2.8% 범위 내 등락. 하반기 인하 기대감은 유효.",
    tags: ["채권", "금리", "금통위"],
  },
  {
    id: "rr-003",
    region: "foreign",
    title: "US Economics: May CPI Confirms Disinflation Trend",
    publisher: "Goldman Sachs",
    publishedAt: "2026-05-25",
    url: "https://www.goldmansachs.com",
    summary: "April CPI miss supports two cuts in H2. Core services inflation remains sticky but trajectory is encouraging. Maintained 2026 year-end target at 4.0%.",
    tags: ["CPI", "Fed", "미국경제"],
  },
  {
    id: "rr-004",
    region: "foreign",
    title: "China Trade: 90-day Pause Opens Window for Structural Talks",
    publisher: "Morgan Stanley",
    publishedAt: "2026-05-25",
    url: "https://www.morganstanley.com",
    summary: "The tariff pause reduces near-term downside for Asian equities and EM FX. However, structural tensions remain unresolved. Upgrading China to Equal Weight.",
    tags: ["중국", "무역", "아시아"],
  },
  {
    id: "rr-005",
    region: "domestic",
    title: "부동산 시장 리뷰: 서울 아파트 거래량 3개월 연속 증가",
    publisher: "미래에셋증권",
    publishedAt: "2026-05-24",
    url: "https://www.miraeasset.com",
    summary: "4월 서울 아파트 거래량 5,823건으로 전월 대비 +8.2%. DSR 3단계 시행 전 막바지 수요 집중. 강남 3구 중심 가격 반등.",
    tags: ["부동산", "아파트", "서울"],
  },
  {
    id: "rr-006",
    region: "foreign",
    title: "Oil Market Outlook: OPEC+ Supply Increase Weighs on Prices",
    publisher: "JP Morgan",
    publishedAt: "2026-05-24",
    url: "https://www.jpmorgan.com",
    summary: "OPEC+ June output hike of 411kbd likely to keep WTI below $65. Demand recovery in China is key upside risk. Revised H2 2026 WTI forecast to $62-68.",
    tags: ["유가", "OPEC", "원자재"],
  },
];

// ────────────────────────────────────────────
// 경제지표 발표 일정 (2026-05-25 기준 향후 3주)
// ────────────────────────────────────────────
export const economicEvents: EconomicEvent[] = [
  // ── 5월 26일 (월) ──────────────────────────
  {
    id: "ev-001",
    indicatorId: "us-10y",
    name: "미국 내구재 수주 (4월)",
    nameEn: "US Durable Goods Orders",
    region: "foreign",
    scheduledDate: "2026-05-26",
    scheduledTime: "21:30",
    importance: "medium",
    previous: "+0.9%",
    forecast: "+0.5%",
    source: "U.S. Census Bureau",
    category: "성장",
  },
  {
    id: "ev-002",
    indicatorId: "us-gdp",
    name: "미국 GDP 2차 추정 (1Q26)",
    nameEn: "US GDP 2nd Estimate Q1 2026",
    region: "foreign",
    scheduledDate: "2026-05-26",
    scheduledTime: "21:30",
    importance: "high",
    previous: "-0.3%",
    forecast: "-0.2%",
    source: "BEA",
    category: "성장",
  },

  // ── 5월 27일 (화) ──────────────────────────
  {
    id: "ev-003",
    indicatorId: "us-cpi",
    name: "미국 컨퍼런스보드 소비자신뢰지수 (5월)",
    nameEn: "US CB Consumer Confidence",
    region: "foreign",
    scheduledDate: "2026-05-27",
    scheduledTime: "23:00",
    importance: "medium",
    previous: "85.7",
    forecast: "87.5",
    source: "Conference Board",
    category: "성장",
  },

  // ── 5월 28일 (수) ──────────────────────────
  {
    id: "ev-004",
    indicatorId: "kor-cpi",
    name: "한국 소비자물가지수 (5월)",
    nameEn: "Korea CPI May",
    region: "domestic",
    scheduledDate: "2026-05-28",
    scheduledTime: "08:00",
    importance: "high",
    previous: "1.9%",
    forecast: "1.8%",
    source: "통계청",
    category: "물가",
  },
  {
    id: "ev-005",
    indicatorId: "us-pce",
    name: "미국 PCE 물가 (4월)",
    nameEn: "US Core PCE Price Index",
    region: "foreign",
    scheduledDate: "2026-05-28",
    scheduledTime: "21:30",
    importance: "high",
    previous: "2.6%",
    forecast: "2.5%",
    source: "BEA",
    category: "물가",
  },

  // ── 5월 29일 (목) ──────────────────────────
  {
    id: "ev-006",
    indicatorId: "kor-current-account",
    name: "한국 경상수지 (3월)",
    nameEn: "Korea Current Account",
    region: "domestic",
    scheduledDate: "2026-05-29",
    scheduledTime: "08:00",
    importance: "medium",
    previous: "68.4억달러",
    forecast: "65.0억달러",
    source: "한국은행",
    category: "신용",
  },
  {
    id: "ev-007",
    indicatorId: "us-unemployment",
    name: "미국 신규 실업수당 청구건수",
    nameEn: "US Initial Jobless Claims",
    region: "foreign",
    scheduledDate: "2026-05-29",
    scheduledTime: "21:30",
    importance: "medium",
    previous: "229천건",
    forecast: "225천건",
    source: "DOL",
    category: "고용",
  },

  // ── 6월 2일 (월) ──────────────────────────
  {
    id: "ev-008",
    indicatorId: "kor-m2",
    name: "한국 광의통화(M2) (4월)",
    nameEn: "Korea M2 Money Supply",
    region: "domestic",
    scheduledDate: "2026-06-02",
    scheduledTime: "08:00",
    importance: "low",
    previous: "3,987조원",
    forecast: "4,010조원",
    source: "한국은행",
    category: "유동성",
  },
  {
    id: "ev-009",
    indicatorId: "sp500",
    name: "미국 ISM 제조업 PMI (5월)",
    nameEn: "US ISM Manufacturing PMI",
    region: "foreign",
    scheduledDate: "2026-06-02",
    scheduledTime: "23:00",
    importance: "high",
    previous: "48.7",
    forecast: "49.5",
    source: "ISM",
    category: "성장",
  },

  // ── 6월 4일 (수) ──────────────────────────
  {
    id: "ev-010",
    indicatorId: "us-nonfarm",
    name: "미국 ADP 민간고용 (5월)",
    nameEn: "US ADP Employment",
    region: "foreign",
    scheduledDate: "2026-06-04",
    scheduledTime: "21:15",
    importance: "medium",
    previous: "155천명",
    forecast: "140천명",
    source: "ADP",
    category: "고용",
  },
  {
    id: "ev-011",
    indicatorId: "sp500",
    name: "미국 ISM 서비스업 PMI (5월)",
    nameEn: "US ISM Services PMI",
    region: "foreign",
    scheduledDate: "2026-06-04",
    scheduledTime: "23:00",
    importance: "medium",
    previous: "51.6",
    forecast: "52.0",
    source: "ISM",
    category: "성장",
  },

  // ── 6월 5일 (목) ──────────────────────────
  {
    id: "ev-012",
    indicatorId: "kor-gdp",
    name: "한국 GDP 성장률 확정 (1Q26)",
    nameEn: "Korea GDP Final Q1 2026",
    region: "domestic",
    scheduledDate: "2026-06-05",
    scheduledTime: "08:00",
    importance: "high",
    previous: "1.2%",
    forecast: "1.1%",
    source: "한국은행",
    category: "성장",
  },
  {
    id: "ev-013",
    indicatorId: "us-nonfarm",
    name: "미국 비농업 고용 (5월)",
    nameEn: "US Nonfarm Payrolls",
    region: "foreign",
    scheduledDate: "2026-06-05",
    scheduledTime: "21:30",
    importance: "high",
    previous: "177천명",
    forecast: "160천명",
    source: "BLS",
    category: "고용",
  },
  {
    id: "ev-014",
    indicatorId: "us-unemployment",
    name: "미국 실업률 (5월)",
    nameEn: "US Unemployment Rate",
    region: "foreign",
    scheduledDate: "2026-06-05",
    scheduledTime: "21:30",
    importance: "high",
    previous: "4.2%",
    forecast: "4.2%",
    source: "BLS",
    category: "고용",
  },

  // ── 6월 10일 (화) ──────────────────────────
  {
    id: "ev-015",
    indicatorId: "kor-ppi",
    name: "한국 생산자물가지수 (5월)",
    nameEn: "Korea PPI May",
    region: "domestic",
    scheduledDate: "2026-06-10",
    scheduledTime: "06:00",
    importance: "medium",
    previous: "1.4%",
    forecast: "1.3%",
    source: "한국은행",
    category: "물가",
  },

  // ── 6월 11일 (수) ──────────────────────────
  {
    id: "ev-016",
    indicatorId: "us-cpi",
    name: "미국 소비자물가지수 (5월)",
    nameEn: "US CPI May",
    region: "foreign",
    scheduledDate: "2026-06-11",
    scheduledTime: "21:30",
    importance: "high",
    previous: "2.3%",
    forecast: "2.2%",
    source: "BLS",
    category: "물가",
  },

  // ── 6월 12일 (목) ──────────────────────────
  {
    id: "ev-017",
    indicatorId: "fed-rate",
    name: "FOMC 기준금리 결정",
    nameEn: "FOMC Interest Rate Decision",
    region: "foreign",
    scheduledDate: "2026-06-12",
    scheduledTime: "03:00",
    importance: "high",
    previous: "4.25~4.50%",
    forecast: "4.25~4.50% (동결)",
    source: "Federal Reserve",
    category: "금리",
  },

  // ── 6월 13일 (금) ──────────────────────────
  {
    id: "ev-018",
    indicatorId: "kor-base-rate",
    name: "한국은행 금융통화위원회",
    nameEn: "Bank of Korea MPC",
    region: "domestic",
    scheduledDate: "2026-06-13",
    scheduledTime: "10:00",
    importance: "high",
    previous: "2.75%",
    forecast: "2.75% (동결)",
    source: "한국은행",
    category: "금리",
  },
  {
    id: "ev-019",
    indicatorId: "kor-unemployment",
    name: "한국 고용동향 (5월)",
    nameEn: "Korea Employment Trend",
    region: "domestic",
    scheduledDate: "2026-06-13",
    scheduledTime: "08:00",
    importance: "medium",
    previous: "3.1%",
    forecast: "3.0%",
    source: "통계청",
    category: "고용",
  },
];

// ────────────────────────────────────────────
// 통합 내보내기
// ────────────────────────────────────────────
export const allIndicators: EconomicIndicator[] = [
  ...domesticIndicators,
  ...foreignIndicators,
];

export const TODAY = _TODAY;

export const CATEGORY_COLORS: Record<string, string> = {
  주가: "text-blue-400",
  환율: "text-purple-400",
  금리: "text-yellow-400",
  물가: "text-red-400",
  고용: "text-orange-400",
  성장: "text-green-400",
  가격: "text-amber-400",
  기타: "text-slate-400",
};

export const CATEGORY_BG: Record<string, string> = {
  주가: "bg-blue-400/10 border-blue-400/20",
  환율: "bg-purple-400/10 border-purple-400/20",
  금리: "bg-yellow-400/10 border-yellow-400/20",
  물가: "bg-red-400/10 border-red-400/20",
  고용: "bg-orange-400/10 border-orange-400/20",
  성장: "bg-green-400/10 border-green-400/20",
  가격: "bg-amber-400/10 border-amber-400/20",
  기타: "bg-slate-400/10 border-slate-400/20",
};

// 카테고리 표시 순서
export const CATEGORY_ORDER = ["주가", "환율", "금리", "물가", "고용", "성장", "가격", "기타"];

// 카테고리 hex 색상 (컴포넌트 inline style용)
export const CATEGORY_HEX: Record<string, string> = {
  주가: "#60a5fa",
  환율: "#c084fc",
  금리: "#facc15",
  물가: "#f87171",
  고용: "#fb923c",
  성장: "#4ade80",
  가격: "#fbbf24",
  기타: "#94a3b8",
};
